//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionStock.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatabaseArticle
    {
        public string Reference { get; set; }
        public string Designation { get; set; }
        public decimal PrixVente { get; set; }
        public decimal QteStock { get; set; }
        public bool Sommeil { get; set; }
    }
}
